import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkGfm from 'remark-gfm';
import remarkHtml from 'remark-html';
import type { Plugin } from 'vite';

const POSTS_DIR = path.resolve(__dirname, '../posts');
const GENERATED_DIR = path.resolve(__dirname, '../.generated');

const VIRTUAL_BLOG_INDEX = 'virtual:blog-index';
const VIRTUAL_POST_MAP = 'virtual:post-map';
const VIRTUAL_BLOG_POST_PREFIX = 'virtual:blog-post:';

interface PostData {
    slug: string;
    frontmatter: Record<string, string | string[] | boolean | number>;
    content: string;
}

async function compileMarkdown(content: string): Promise<string> {
    const result = await unified()
        .use(remarkParse)
        .use(remarkGfm)
        .use(remarkHtml, { sanitize: false })
        .process(content);
    return String(result);
}

function parseAllPosts(): PostData[] {
    if (!fs.existsSync(POSTS_DIR)) return [];
    const files = fs.readdirSync(POSTS_DIR).filter(f => f.endsWith('.md'));
    return files.map(file => {
        const raw = fs.readFileSync(path.join(POSTS_DIR, file), 'utf-8');
        const { data, content } = matter(raw);
        return {
            slug: file.replace(/\.md$/, ''),
            frontmatter: data,
            content,
        };
    });
}

function generatePostMap(posts: PostData[]): string {
    const entries = posts
        .filter(p => !p.frontmatter.draft)
        .map(p => `  '${p.slug}': () => import('${VIRTUAL_BLOG_POST_PREFIX}${p.slug}')`)
        .join(',\n');
    return `// Auto-generated by plugins/markdown.ts — do not edit
export default {
${entries}
} as Record<string, () => Promise<{ default: { frontmatter: Record<string, any>; html: string } }>>;
`;
}

export function markdownPlugin(): Plugin {
    const postsCache = new Map<string, { frontmatter: Record<string, string | string[] | boolean | number>; html: string }>();

    return {
        name: 'vite-plugin-markdown-blog',

        configureServer(server) {
            // 监听 posts 目录变化，使虚拟模块缓存失效。
            // chokidar 在 Windows 上可能上报正斜杠路径，先 path.resolve 归一化再比较。
            const isPostFile = (file: string) => {
                const resolved = path.resolve(file);
                return resolved.startsWith(POSTS_DIR + path.sep) && resolved.endsWith('.md');
            };
            /** 重编译指定文章入缓存（draft 则移除），并失效相关虚拟模块 + 整页刷新 */
            const syncPost = (slug: string) => {
                const filePath = path.join(POSTS_DIR, slug + '.md');
                if (fs.existsSync(filePath)) {
                    const raw = fs.readFileSync(filePath, 'utf-8');
                    const { data, content } = matter(raw);
                    if (data.draft) {
                        postsCache.delete(slug);
                    } else {
                        compileMarkdown(content).then(html => {
                            postsCache.set(slug, { frontmatter: data, html });
                        });
                    }
                } else {
                    postsCache.delete(slug);
                }
                const { moduleGraph } = server;
                const invalidate = (id: string) => {
                    const mod = moduleGraph.getModuleById('\0' + id);
                    if (mod) moduleGraph.invalidateModule(mod);
                };
                invalidate(VIRTUAL_BLOG_INDEX);
                invalidate(VIRTUAL_POST_MAP);
                invalidate(VIRTUAL_BLOG_POST_PREFIX + slug);
                server.ws.send({ type: 'full-reload' });
            };

            server.watcher.add(POSTS_DIR);
            server.watcher.on('add', (file) => {
                if (isPostFile(file)) syncPost(path.basename(file, '.md'));
            });
            server.watcher.on('change', (file) => {
                if (isPostFile(file)) syncPost(path.basename(file, '.md'));
            });
            server.watcher.on('unlink', (file) => {
                if (isPostFile(file)) syncPost(path.basename(file, '.md'));
            });
        },

        async buildStart() {
            const posts = parseAllPosts();
            // Generate post-map file
            if (!fs.existsSync(GENERATED_DIR)) {
                fs.mkdirSync(GENERATED_DIR, { recursive: true });
            }
            fs.writeFileSync(
                path.join(GENERATED_DIR, 'post-map.ts'),
                generatePostMap(posts)
            );
            // Pre-compile all posts for virtual module access
            for (const post of posts) {
                if (!post.frontmatter.draft) {
                    const html = await compileMarkdown(post.content);
                    postsCache.set(post.slug, { frontmatter: post.frontmatter, html });
                }
            }
        },

        resolveId(id) {
            if (id === VIRTUAL_BLOG_INDEX) {
                return '\0' + VIRTUAL_BLOG_INDEX;
            }
            if (id === VIRTUAL_POST_MAP) {
                return '\0' + VIRTUAL_POST_MAP;
            }
            if (id.startsWith(VIRTUAL_BLOG_POST_PREFIX)) {
                return '\0' + id;
            }
        },

        load(id) {
            if (id === '\0' + VIRTUAL_POST_MAP) {
                const posts = parseAllPosts().filter(p => !p.frontmatter.draft);
                const entries = posts
                    .map(p => `  '${p.slug}': () => import('${VIRTUAL_BLOG_POST_PREFIX}${p.slug}')`)
                    .join(',\n');
                return `export default {${entries}};`;
            }

            if (id === '\0' + VIRTUAL_BLOG_INDEX) {
                const posts = parseAllPosts();
                const index = posts
                    .filter(p => !p.frontmatter.draft)
                    .sort((a, b) =>
                        new Date(b.frontmatter.date as string).getTime() - new Date(a.frontmatter.date as string).getTime()
                    )
                    .map(p => ({ slug: p.slug, ...p.frontmatter }));
                return `export default ${JSON.stringify(index)}`;
            }

            if (id.startsWith('\0' + VIRTUAL_BLOG_POST_PREFIX)) {
                const slug = id.replace('\0' + VIRTUAL_BLOG_POST_PREFIX, '');
                const cached = postsCache.get(slug);
                if (cached) {
                    return `export default ${JSON.stringify(cached)}`;
                }
                // 未缓存时从文件读取
                const filePath = path.join(POSTS_DIR, slug + '.md');
                if (fs.existsSync(filePath)) {
                    const raw = fs.readFileSync(filePath, 'utf-8');
                    const { data, content } = matter(raw);
                    return `export default ${JSON.stringify({ frontmatter: data, html: content })}`;
                }
                return `export default null`;
            }
        },
    };
}
